package com.example.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class DataInitializer {

    private static final Logger log = LoggerFactory.getLogger(DataInitializer.class);

    @Bean
    public CommandLineRunner initDatabase(JdbcTemplate jdbcTemplate) {
        return args -> {
            try {
                // ── 用户表 ──
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(50) NOT NULL UNIQUE,
                        password VARCHAR(100) NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        name VARCHAR(50),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // ── 公告表 ──
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS notice (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        content CLOB NOT NULL,
                        publish_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // ── 聊天会话表 ──
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS chat_session (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        title VARCHAR(255) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // ── 聊天消息表 ──
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS chat_message (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        content CLOB NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // 初始化用户
                Integer userCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM users", Integer.class);
                if (userCount != null && userCount == 0) {
                    jdbcTemplate.update("INSERT INTO users (username, password, role, name) VALUES (?, ?, ?, ?)",
                            "laoshi", "123456", "teacher", "张老师");
                    jdbcTemplate.update("INSERT INTO users (username, password, role, name) VALUES (?, ?, ?, ?)",
                            "xuesheng", "654321", "student", "李同学");
                    log.info("已创建教师和学生账号");
                }

                // 检查是否已有公告数据
                Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM notice", Integer.class);
                if (count != null && count == 0) {
                    jdbcTemplate.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, ?)",
                            "期末考试安排", "2026年春季学期期末考试将于7月1日至7月10日进行，请同学们提前做好复习准备。", "2026-06-10 09:00:00");
                    jdbcTemplate.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, ?)",
                            "校园网络维护通知", "本周六晚22:00至次日6:00进行校园网络升级维护，届时校园网将中断，请提前做好准备。", "2026-06-09 14:00:00");
                    jdbcTemplate.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, ?)",
                            "图书馆暑期开放安排", "暑假期间图书馆开放时间调整为周一至周五 8:00-18:00，周末闭馆。", "2026-06-08 10:00:00");
                    jdbcTemplate.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, ?)",
                            "奖学金评选结果公示", "2025-2026学年奖学金评选结果已公示在教务系统，如有异议请于6月20日前提交申诉。", "2026-06-07 16:00:00");
                    jdbcTemplate.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, ?)",
                            "毕业生离校手续办理", "2026届毕业生请于6月25日前完成离校手续办理，包括归还图书、结算费用等。", "2026-06-05 08:30:00");
                    log.info("已插入 5 条示例公告");
                } else {
                    log.info("公告表已有 {} 条数据，跳过初始化", count);
                }
            } catch (Exception e) {
                log.error("数据库初始化失败", e);
            }
        };
    }
}
