package com.example.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class DataInitializer {

    private static final Logger log = LoggerFactory.getLogger(DataInitializer.class);

    @Bean
    public CommandLineRunner initDatabase(JdbcTemplate jdbcTemplate) {
        return args -> {
            try {
                // 先删旧表（解决表结构变更导致的列不匹配问题）
                jdbcTemplate.execute("DROP TABLE IF EXISTS grade CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS course CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS student CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS teacher CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS notice CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS chat_message CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS chat_session CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS users CASCADE");

                // ====== 教师表 ======
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS teacher (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        teacher_no VARCHAR(20) NOT NULL UNIQUE,
                        name VARCHAR(50) NOT NULL,
                        password VARCHAR(100) NOT NULL DEFAULT '123456',
                        enrollment_year INT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // ====== 学生表 ======
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS student (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        student_no VARCHAR(20) NOT NULL UNIQUE,
                        name VARCHAR(50) NOT NULL,
                        password VARCHAR(100) NOT NULL DEFAULT '123456',
                        major VARCHAR(100),
                        class_name VARCHAR(50),
                        enrollment_year INT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // ====== 课程表 ======
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS course (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        course_code VARCHAR(20) NOT NULL,
                        course_name VARCHAR(100) NOT NULL,
                        major VARCHAR(100),
                        semester VARCHAR(20),
                        credits DOUBLE PRECISION,
                        teacher_id BIGINT,
                        schedule_day VARCHAR(10),
                        schedule_time VARCHAR(30),
                        classroom VARCHAR(50)
                    )
                    """);

                // ====== 成绩表 ======
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS grade (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        student_id BIGINT NOT NULL,
                        course_id BIGINT NOT NULL,
                        score DOUBLE PRECISION,
                        grade_point DOUBLE PRECISION,
                        semester VARCHAR(20)
                    )
                    """);

                // ====== 公告表 ======
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS notice (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        content TEXT NOT NULL,
                        publish_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // ====== 聊天会话 ======
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS chat_session (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        title VARCHAR(255) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
                jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS chat_message (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        content TEXT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

                // 清空 + 种子数据
                seedAll(jdbcTemplate);

            } catch (Exception e) {
                log.error("数据库初始化失败", e);
            }
        };
    }

    private void seedAll(JdbcTemplate j) {
        // 清空向量库脏数据
        try { j.update("DELETE FROM vector_store"); } catch (Exception ignored) {}

        // ==================== 教师（9人） ====================
        Object[][] teachers = {
            {"1202001", "蒋老师", 2020}, {"1202102", "周老师", 2021},
            {"1302003", "王老师", 2020}, {"1302104", "李老师", 2021},
            {"1302205", "张老师", 2022}, {"1302306", "刘老师", 2020},
            {"1402007", "赵老师", 2020}, {"1402108", "孙老师", 2021},
            {"1402209", "钱老师", 2022}
        };
        for (Object[] t : teachers) {
            j.update("INSERT INTO teacher (teacher_no, name, password, enrollment_year) VALUES (?, ?, '123456', ?)", t);
        }
        log.info("已创建 {} 名教师", teachers.length);

        // ==================== 学生（5人） ====================
        Object[][] students = {
            {"325010101", "张明远", "物联网工程", "物联网1班", 2025},
            {"325010102", "李思敏", "物联网工程", "物联网1班", 2025},
            {"325010103", "王旭东", "物联网工程", "物联网1班", 2025},
            {"325030101", "陈子萱", "法学", "法学1班", 2025},
            {"325030102", "赵一航", "法学", "法学1班", 2025},
        };
        for (Object[] s : students) {
            j.update("INSERT INTO student (student_no, name, password, major, class_name, enrollment_year) VALUES (?, ?, '123456', ?, ?, ?)", s);
        }
        log.info("已创建 {} 名学生", students.length);

        // ==================== 课程 ====================
        // 教师ID 查询: SELECT id FROM teacher WHERE teacher_no = ?
        // 物联网工程课程（major=物联网工程）
        Object[][] iotCourses = {
            {"CS201", "Java程序设计",  "物联网工程", 4.0, "1202001", "周一", "1-2节",  "A201"},
            {"MATH101","高等数学",     "物联网工程", 3.0, "1302003", "周一", "3-4节",  "A103"},
            {"ENG101", "大学英语",     "物联网工程", 2.0, "1302003", "周二", "1-2节",  "B101"},
            {"CS202", "数据库原理",    "物联网工程", 3.0, "1302104", "周三", "1-2节",  "B203"},
            {"CS203", "Web开发技术",   "物联网工程", 3.0, "1202001", "周三", "3-4节",  "B305"},
            {"CS204", "计算机网络",    "物联网工程", 3.5, "1302104", "周四", "1-2节",  "B204"},
            {"POL101", "思想道德修养", "物联网工程", 2.0, "1302306", "周四", "3-4节",  "A202"},
            {"IOT201","物联网导论",   "物联网工程", 3.0, "1302205", "周五", "1-2节",  "A301"},
            {"IOT202","传感器技术",   "物联网工程", 3.0, "1302205", "周五", "3-4节",  "A302"},
        };
        // 法学课程（major=法学）
        Object[][] lawCourses = {
            {"CHN101", "大学语文",         "法学", 2.0, "1402108", "周一", "1-2节",  "C201"},
            {"LAW101", "法理学",           "法学", 3.0, "1202102", "周一", "3-4节",  "C101"},
            {"ENG102", "大学英语",         "法学", 2.0, "1402108", "周二", "1-2节",  "C202"},
            {"LAW102", "刑法学",           "法学", 3.0, "1402007", "周二", "3-4节",  "C102"},
            {"LAW103", "民法学",           "法学", 3.0, "1202102", "周三", "1-2节",  "C103"},
            {"LAW104", "宪法学",           "法学", 3.0, "1402007", "周三", "3-4节",  "C104"},
            {"LAW105", "行政法学",         "法学", 3.0, "1402108", "周四", "1-2节",  "C105"},
            {"HIS101", "中国近现代史纲要", "法学", 2.0, "1402209", "周四", "3-4节",  "C106"},
            {"POL102", "思想道德修养",     "法学", 2.0, "1302306", "周五", "1-2节",  "C107"},
        };

        for (Object[][] courses : new Object[][][]{iotCourses, lawCourses}) {
            for (Object[] c : courses) {
                Long tid = j.queryForObject("SELECT id FROM teacher WHERE teacher_no = ?", Long.class, c[4]);
                j.update("INSERT INTO course (course_code, course_name, major, credits, teacher_id, schedule_day, schedule_time, classroom, semester) VALUES (?,?,?,?,?,?,?,?, '2025-2026-2')",
                        c[0], c[1], c[2], c[3], tid, c[5], c[6], c[7]);
            }
        }
        log.info("已创建 18 门课程");

        // ==================== 成绩 ====================
        // 张明远 (325010101)
        insertGrade(j, "325010101", "CS201", 87);  insertGrade(j, "325010101", "MATH101", 78);
        insertGrade(j, "325010101", "ENG101", 82);  insertGrade(j, "325010101", "CS202", 91);
        insertGrade(j, "325010101", "CS203", 92);   insertGrade(j, "325010101", "CS204", 85);
        insertGrade(j, "325010101", "POL101", 88);  insertGrade(j, "325010101", "IOT201", 79);
        insertGrade(j, "325010101", "IOT202", 84);
        // 李思敏 (325010102)
        insertGrade(j, "325010102", "CS201", 78);   insertGrade(j, "325010102", "MATH101", 65);
        insertGrade(j, "325010102", "ENG101", 88);  insertGrade(j, "325010102", "CS202", 74);
        insertGrade(j, "325010102", "CS203", 85);   insertGrade(j, "325010102", "CS204", 79);
        insertGrade(j, "325010102", "POL101", 92);  insertGrade(j, "325010102", "IOT201", 81);
        insertGrade(j, "325010102", "IOT202", 77);
        // 王旭东 (325010103)
        insertGrade(j, "325010103", "CS201", 94);   insertGrade(j, "325010103", "MATH101", 89);
        insertGrade(j, "325010103", "ENG101", 76);  insertGrade(j, "325010103", "CS202", 96);
        insertGrade(j, "325010103", "CS203", 88);   insertGrade(j, "325010103", "CS204", 91);
        insertGrade(j, "325010103", "POL101", 85);  insertGrade(j, "325010103", "IOT201", 93);
        insertGrade(j, "325010103", "IOT202", 90);
        // 陈子萱 (325030101)
        insertGrade(j, "325030101", "CHN101", 85);  insertGrade(j, "325030101", "LAW101", 81);
        insertGrade(j, "325030101", "ENG102", 79);  insertGrade(j, "325030101", "LAW102", 88);
        insertGrade(j, "325030101", "LAW103", 79);  insertGrade(j, "325030101", "LAW104", 83);
        insertGrade(j, "325030101", "LAW105", 76);  insertGrade(j, "325030101", "HIS101", 90);
        insertGrade(j, "325030101", "POL102", 87);
        // 赵一航 (325030102)
        insertGrade(j, "325030102", "CHN101", 72);  insertGrade(j, "325030102", "LAW101", 68);
        insertGrade(j, "325030102", "ENG102", 65);  insertGrade(j, "325030102", "LAW102", 74);
        insertGrade(j, "325030102", "LAW103", 74);  insertGrade(j, "325030102", "LAW104", 70);
        insertGrade(j, "325030102", "LAW105", 69);  insertGrade(j, "325030102", "HIS101", 80);
        insertGrade(j, "325030102", "POL102", 75);
        log.info("已创建 45 条成绩记录");

        // ==================== 公告 ====================
        j.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, CAST(? AS TIMESTAMP))",
                "期末考试安排", "2026年春季学期期末考试将于7月1日至7月10日进行，请同学们提前做好复习准备。", "2026-06-10 09:00:00");
        j.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, CAST(? AS TIMESTAMP))",
                "校园网络维护通知", "本周六晚22:00至次日6:00进行校园网络升级维护，届时校园网将中断，请提前做好准备。", "2026-06-09 14:00:00");
        j.update("INSERT INTO notice (title, content, publish_time) VALUES (?, ?, CAST(? AS TIMESTAMP))",
                "图书馆暑期开放安排", "暑假期间图书馆开放时间调整为周一至周五 8:00-18:00，周末闭馆。", "2026-06-08 10:00:00");
        log.info("已插入 3 条公告");
    }

    /** 成绩插入：用学号和课程编号查 ID */
    private void insertGrade(JdbcTemplate j, String studentNo, String courseCode, double score) {
        double gp = score >= 90 ? 4.0 : score >= 85 ? 3.7 : score >= 82 ? 3.3 :
                    score >= 78 ? 3.0 : score >= 75 ? 2.7 : score >= 72 ? 2.3 :
                    score >= 68 ? 2.0 : score >= 64 ? 1.5 : score >= 60 ? 1.0 : 0.0;
        j.update("INSERT INTO grade (student_id, course_id, score, grade_point, semester) " +
                "SELECT s.id, c.id, ?, ?, '2025-2026-2' FROM student s, course c " +
                "WHERE s.student_no = ? AND c.course_code = ?", score, gp, studentNo, courseCode);
    }
}
